DROP TABLE IF EXISTS COUNTRIES;

CREATE TABLE COUNTRIES (
    NAME VARCHAR(255) NOT NULL,
    POPULATION INT NULL,
    CAPITAL VARCHAR(255) NULL,
    CURRENCY VARCHAR(3) NULL,
    PRIMARY KEY (NAME)
);

INSERT INTO COUNTRIES (NAME, POPULATION, CAPITAL, CURRENCY) VALUES
    ('SINGAPORE', 40000000, '', 'SGD'),
    ('INDONESIA', 1000000000, 'JAKARTA', 'IDR'),
    ('MALAYSIA', 70000000, 'KUALA LUMPUR', 'RM');
